name:                shortly
version:             0.1.0.0
github:              "githubuser/shortly"
license:             MIT
author:              "Muryllo Pimenta de Oliveira"
maintainer:          "muryllo.pimenta@upe.br"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/shortly#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  shortly-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shortly
    - aeson
    - binary
    - text
    - scotty
    - random
    - mysql-simple
    - resource-pool
    - ghc-prim
    - mysql
    

tests:
  shortly-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shortly
    - hspec
    - QuickCheck
    - text
